[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.deny]
install_crate = "cargo-deny"
command = "cargo"
args = ["deny", "check"]

[tasks.typos]
install_crate = "typos-cli"
command = "typos"
dependencies = ["deny"]

[tasks.check]
command = "cargo"
args = ["check", "--all"]
dependencies = ["typos"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--all-features", "--tests", "--benches", "--", "-D", "warnings"]
dependencies = ["check"]

[tasks.test]
install_crate = "cargo-nextest"
command = "cargo"
args = ["nextest", "run"]
dependencies = ["clippy"]

[tasks.add]
command = "git"
args = ["add", "."]
dependencies = ["test"]

[tasks.commit]
command = "git"
args = ["commit", "-a"]
dependencies = ["add"]

[tasks.cliff]
install_crate = "git-cliff"
command = "git"
args = ["cliff", "-o", "CHANGELOG.md"]
dependencies = ["commit"]

[tasks.do]
dependencies = [
    "format",
    "deny",
    "typos",
    "check",
    "clippy",
    "test",
    "commit",
    "cliff"
]
